// Mocks generated by Mockito 5.4.6 from annotations
// in puvadon_jenosize/test/modules/campaign_module/mock/campaign_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// Dart imports:
import 'dart:async' as _i3;

// Package imports:
import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

import 'package:puvadon_jenosize/src/core/errors/models/failure_model.dart'
    as _i5;
import 'package:puvadon_jenosize/src/modules/campaign_module/data/data_sources/remote/campaign_remote_data_source.dart'
    as _i2;
import 'package:puvadon_jenosize/src/modules/campaign_module/data/models/campaign_list_model.dart'
    as _i6;
import 'package:puvadon_jenosize/src/modules/campaign_module/domain/entities/campaing_entities.dart'
    as _i9;
import 'package:puvadon_jenosize/src/modules/campaign_module/domain/repositories/campaign_remote_repositories.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CampaignRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampaignRemoteDataSource extends _i1.Mock
    implements _i2.CampaignRemoteDataSource {
  @override
  _i3.Future<_i4.Either<_i5.FailureModel, _i6.CampaignListModel>>
  fetchCampaignData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCampaignData, []),
            returnValue: _i3.Future<
              _i4.Either<_i5.FailureModel, _i6.CampaignListModel>
            >.value(
              _i7.dummyValue<
                _i4.Either<_i5.FailureModel, _i6.CampaignListModel>
              >(this, Invocation.method(#fetchCampaignData, [])),
            ),
            returnValueForMissingStub: _i3.Future<
              _i4.Either<_i5.FailureModel, _i6.CampaignListModel>
            >.value(
              _i7.dummyValue<
                _i4.Either<_i5.FailureModel, _i6.CampaignListModel>
              >(this, Invocation.method(#fetchCampaignData, [])),
            ),
          )
          as _i3.Future<_i4.Either<_i5.FailureModel, _i6.CampaignListModel>>);
}

/// A class which mocks [CampaignRemoteRepositories].
///
/// See the documentation for Mockito's code generation for more information.
class MockCampaignRemoteRepositories extends _i1.Mock
    implements _i8.CampaignRemoteRepositories {
  @override
  _i3.Future<_i4.Either<_i5.FailureModel, List<_i9.CampaignEntities>>>
  getCampaigns() =>
      (super.noSuchMethod(
            Invocation.method(#getCampaigns, []),
            returnValue: _i3.Future<
              _i4.Either<_i5.FailureModel, List<_i9.CampaignEntities>>
            >.value(
              _i7.dummyValue<
                _i4.Either<_i5.FailureModel, List<_i9.CampaignEntities>>
              >(this, Invocation.method(#getCampaigns, [])),
            ),
            returnValueForMissingStub: _i3.Future<
              _i4.Either<_i5.FailureModel, List<_i9.CampaignEntities>>
            >.value(
              _i7.dummyValue<
                _i4.Either<_i5.FailureModel, List<_i9.CampaignEntities>>
              >(this, Invocation.method(#getCampaigns, [])),
            ),
          )
          as _i3.Future<
            _i4.Either<_i5.FailureModel, List<_i9.CampaignEntities>>
          >);
}
